### ISSUE TITLE
No module named 'pointpillars'

### ISSUE THREAD

**Issue by ZoranDai** [chenyirui/FASTC#1]
您好，当我尝试运行代码时发现没有pointpillars这个库，请问可以如何下载？
```
bash train_single.sh /mnt/data/FASTC/experiment/rellis4_100/single/default.yaml
Traceback (most recent call last):
  File "/mnt/data/FASTC/FASTC/train_single.py", line 9, in <module>
    import networks
  File "/mnt/data/FASTC/FASTC/networks.py", line 6, in <module>
    import pointpillars
ModuleNotFoundError: No module named 'pointpillars'
```

**Comment by chenyirui** [comment]
> 您好，当我尝试运行代码时发现这个库没有pointpillars，请问如何下载？
> 
> ```
> bash train_single.sh /mnt/data/FASTC/experiment/rellis4_100/single/default.yaml
> Traceback (most recent call last):
>   File "/mnt/data/FASTC/FASTC/train_single.py", line 9, in <module>
>     import networks
>   File "/mnt/data/FASTC/FASTC/networks.py", line 6, in <module>
>     import pointpillars
> ModuleNotFoundError: No module named 'pointpillars'
> ```

您好，

感谢您反馈问题。确实，当前环境中缺少 pointpillars 库，导致代码无法正常运行。我会尽快更新相关文件和依赖，解决这个问题。

感谢您的耐心等待！

**Comment by chenyirui** [comment]
> 您好，当我尝试运行代码时发现这个库没有pointpillars，请问如何下载？
> 
> ```
> bash train_single.sh /mnt/data/FASTC/experiment/rellis4_100/single/default.yaml
> Traceback (most recent call last):
>   File "/mnt/data/FASTC/FASTC/train_single.py", line 9, in <module>
>     import networks
>   File "/mnt/data/FASTC/FASTC/networks.py", line 6, in <module>
>     import pointpillars
> ModuleNotFoundError: No module named 'pointpillars'
> ```

您好，

感谢您反馈问题。确实，当前环境中缺少 pointpillars 库，导致代码无法正常运行。我会尽快更新相关文件和依赖，解决这个问题。

**Comment by chenyirui** [comment]
> 您好，当我尝试运行代码时发现没有pointpillars这个库，请问可以如何下载？
> 
> ```
> bash train_single.sh /mnt/data/FASTC/experiment/rellis4_100/single/default.yaml
> Traceback (most recent call last):
>   File "/mnt/data/FASTC/FASTC/train_single.py", line 9, in <module>
>     import networks
>   File "/mnt/data/FASTC/FASTC/networks.py", line 6, in <module>
>     import pointpillars
> ModuleNotFoundError: No module named 'pointpillars'
> ```

你好，抱歉迟复，相关的 pointpillars 库已经加到更新中的代码里了。如果您还有任何其他的问题，请随时告诉我。
